language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"
install:
  - sudo apt-get install pdftk
  - composer install
  - composer require mikehaertl/pdftk2-precise-amd64
  - sudo cp vendor/bin/pdftk /usr/bin/
